config/routes.rb
Rails.application.routes.draw do 
 root   'homepage#index'
 get    '/login',   to: 'sessions#new' 
 post   '/login',   to: 'sessions#create' 
 delete '/logout', to: 'sessions#destroy'  
 
 resources :users
 resources :projects
 resources :categories
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :projects
  default_scope { order(created_at: :desc) }

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :hours, presence: true

  default_scope { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  validates :username, presence: true, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show]
  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show; end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   before_action :set_project, only: %i[show edit update destroy]
    def new
        @project = Project.new
       
    end
      
    def index
       @projects = current_user.projects.includes(:category) 
    end
      
    def create
        @project = current_user.projects.build(project_params)
         if @project.save
            flash[:notice] = "Project Successfully created!"
            redirect_to projects_path
         else
            flash[:notice] = "Project not created!"
            render 'new'
         end
    end

    def show
    end
      
    private
      
    def set_project
         @project = Project.find(params[:id])
    end
        
    def project_params
        params.require(:project).permit(:title, :hours,:category_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(username: params[:session][:username].downcase)
    if @user
      session[:user_id] = @user.id
      flash[:notice] = 'Successfully logged in!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def index 
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            flash[:notice] = "Account Successfully Created!"
            redirect_to @user
        else 
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
    end


    private
    def user_params
        params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

      # Returns the current logged-in user (if any)
   def current_user
    current_user ||= User.find_by(id: session[:user_id] )
   end
    #log in created user
    def login(user)
        session[:user_id] = user.id
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end

    def log_out
        session[:user_id] = nil
    end
end

app/views/categories/_form.html.erb
<h1>Categories</h1>
<%= form_for @category do |f|%>
 <div class="field">
   <%= f.label :name ,class: "col-sm-2 col-form-label font-weight-bold"%>
    <%= f.text_field :name, class: "form-control", placeholder: "Category Name" %>
 </div>
  <div class="field">
     <%= f.label :icon ,class: "col-sm-2 col-form-label font-weight-bold"%>
    <%= f.text_field :icon , class: "form-control", placeholder: "Category Icon"%>
  </div> 
  <br>
  <div>
    <%= f.submit "Add new category", class: "btn btn-outline-primary" %>
  </div> 
  
<%end%>

app/views/categories/index.html.erb
<%= render 'projects/navbar'%>
<h1 class= "text-center">Categories created : <%= @categories.count%></h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Category Name</th>
      <th scope="col">Icon</th>
      <th scope="col">Created</th>
    </tr>
  </thead>
  <tbody>
<% @categories.each do |c|%>
    <tr>
      <th scope="row"><%=%></th>
    
      <td><%= c.name%></td>
      <td><%= c.icon%></td>
      <td><%= c.created_at.strftime("%a-%d-%Y")%></td>
    </tr>
   <%end%>
  </tbody>
</table>

  <div class=" text-center" >
      <%= link_to "Add New Project ", new_project_path, class: "btn btn-outline-primary "%>
      <%= link_to "Back", new_project_path, class: "btn btn-outline-success "%>
  </div>

app/views/categories/new.html.erb
<%= render 'projects/navbar'%>
<div class = "container">
  <%= render 'form'%>
</div>

app/views/homepage/index.html.erb
<div class='container' id='home-container'>
        <div class="jumbotron text-center ">

        <h1 class="display-4 font-weight-bold "><i class="fas fa-edit"></i>Goals_App</h1>

        <p class="lead text-primary font-weight-normal font-italic"> A simple app that lets you group goals or projects and gives an overview of how many each project took .</p>
        <i class="fas fa-list-ol text-primary"></i>  <i class="far fa-clock"></i><i class="fas fa-thumbs-up text-primary "></i>
        <hr class="my-4">
        <p class = 'font-italic font-weight-bold'>Create projects , group them and see how long they took to accomplish at zero cost.</p>
        <%= link_to "Sign Up Now", new_user_path, class:"btn btn-dark btn-lg" %>
        <p class = 'font-italic'> Already a Member? <%= link_to "Login", login_path, class:"btn btn-link"%></p>
    </div>
</div>
<div id = "page-content"></div>
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy;  <a href="github.com/Elukoye">Elukoye</a></small>
    </div>
</footer> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application',  media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column" >
    <% flash.each do |name, msg|%>
    <%= msg %>
    <%end%>
    <%= yield %>
  
  </body>
</html>

app/views/projects/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Goals_App", root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
     <li class="nav-item active">
          <%= link_to current_user.username.capitalize, user_path(current_user) ,class:"nav-link"%>
      </li>
      <li class="nav-item active">
          <%= link_to "Profile", current_user, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Settings</a>
      </li>
      <li class="nav-item ">
         <%= link_to "Logout", logout_path, class:"nav-link", method: :delete%>
      </li>
    </ul>
  </div>
</nav>

app/views/projects/_project_form.html.erb
<%= render partial: '/projects/navbar'%>

<h5 class ="font-weight-bold  text-center">Create a New Project:</h5>

<%= form_for @project do |f|%>
     <div class="field">
        <%= f.label :title, class: "col-sm-2 col-form-label font-weight-bold" %>
        <%= f.text_field :title, class: "form-control", placeholder: "Project Title" %>
    </div>

    <div class="field">
        <%= f.label :hours, class: "col-sm-2 col-form-label font-weight-bold" %>
        <%= f.text_field :hours, class: "form-control", placeholder: "Hours clocked" %>
    </div>
 
     <div class="field">
        <%= f.label :Category, class: "col-sm-2 col-form-label font-weight-bold" %>
        <%= f.select :category_id,Category.all.map{|c| [c.name,c.id]}, class: "form-control", placeholder: "choose category" %>
    </div>
 <br>
     <div class="actions">
        <%= f.submit class: "btn btn-outline-primary " %>
    </div>
<%end%>
<br>
<%= link_to " Add Category", new_category_path, class: "btn btn-outline-secondary"%>

app/views/projects/index.html.erb
<%# A list of all transactions created by logged-in user is displayed (sorted by most recent).%>
<%= render 'navbar'%>
<h1 class= "text-center">Total Projects : <%= @projects.size%></h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Icon</th>
       <th scope="col">category</th>
      <th scope="col">Project Title</th>
      <th scope="col">Hrs</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project|%>
      <%if current_user.projects.any?%>
        <tr>
          <th scope="row"><%=%></th>
          <td><i class="fas fa-couch"></i></td>
          <td><%= project.category.name if project.category %></td>
          <td><%= project.title%></td>
          <td><%= project.hours%></td>
          <td><%= project.created_at.strftime("%a-%d-%Y")%></td>
        </tr>
        <%end%>
    <%end%>
  </tbody>
</table>

  <div class=" text-center" >
      <%= link_to "Add New Project ", new_project_path, class: "btn btn-outline-primary "%>
      <%= link_to "Back", new_project_path, class: "btn btn-outline-success "%>
  </div>

app/views/projects/new.html.erb
<div class= "container">
<%= render  'project_form' %>
</div>

app/views/projects/show.html.erb
<%= @project.title %>
<h3><%= @project.category.category %></h3>

app/views/transactions/index.html.erb
<%# A list of all transactions created by logged-in user is displayed (sorted by most recent).%>
<%= render partial: '/transactions/navbar'%>

<h1 class= "text-center">Total hours :</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Icon</th>
      <th scope="col">Project Title</th>
      <th scope="col">Hrs</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
  <% @transactions.each do |transaction|%>
    <tr>
      <th scope="row"><%=%></th>
      <td><i class="fas fa-couch"></i></td>
      <td><%= transaction.Name%></td>
      <td><%= transaction.Amount%></td>
      <td><%= transaction.created_at.strftime("%a-%d-%Y")%></td>
    </tr>
   <%end%>
  </tbody>
</table>

  <div class=" text-center" >
      <%= link_to "Add New Project ", new_transaction_path, class: "btn btn-outline-primary "%>
      <%= link_to "Back", "#", class: "btn btn-outline-success "%>
  </div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up</h1>

<% if @user.errors.any? %>
   <h6>Fix the following errors:</h6>
   <ul>
      <% @user.errors.full_messages.each do |msg|%>
         <li><%= msg%></li>
      <%end%>
   </ul>
 
<%end%>
<div class = "container">
   <div class="row justify-content-center">
       <%= form_for @user do |f|%>
         <div class="form-group row">
           <%= f.label :username%><br>
         </div>
         <div class="form-group row" >
            <%= f.text_field :username%><br>
         </div>
         <div class="form-group row justify-content-center">
            <%= f.submit "SignUp", class: "btn btn-dark btn-lg" %>
         </div>
        <%end%> 
    </div>
</div>

app/views/users/show.html.erb
<h1 class= "text-center font-weight-normal text-monospace">Your Dashboard </h1>


<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <p> Username: <%= @user.username%></p>
        </div>
        <div class="card-body">
          <div class="card-text text-left"> </div>
          <%= link_to "All my  projects",  projects_path, class: "btn btn-outline-info" %>
          <%= link_to "All  my external projects", projects_path, class: "btn btn-outline-danger"%>
          <%= link_to "All categories", categories_path, class: "btn btn-outline-info" %>
        </div>
        <div class="card-footer text-muted">
            <p><%= link_to "Log out", logout_path, method: "delete" %></p>
        </div>
      </div>
    </div>
  </div>
</div>